version: '3'
volumes:
  node_modules:
services:
  hara_watcher:
    image: hara:watcher
    environment:
      - PRIV_NETWORK=http://192.168.99.100:8546 # connect to private network
      - DB_ENDPOINT=http://192.168.99.100:8000
      - IS_DEV=true
      - RECOVERY=false
      - RECOVERY_START_BLOCK=1
      - RECOVERY_END_BLOCK=300
    command: bash -c "npm run dev && tail -f /dev/null"
    volumes:
      - .:/var/task
      - node_modules:/var/task/node_modules
  
